name = "FileCmp"
uuid = "343a5541-a696-4ae7-8102-bc61c09e1896"
authors = ["John Lapeyre <jlapeyre@users.noreply.github.com> and contributors"]
version = "1.0.0"

[compat]
Aqua = ">= 0.8"
JET = ">= 0.0.1"
Test = ">= 0.0"
julia = "1"

[extras]
Aqua = "4c88cf16-eb10-579e-8560-4a9242c79595"
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test", "Aqua", "JET"]
